/**
 * 组件库 注册表
 * 汇总所有组件定义，暴露全局变量 COMPONENTS 和 COMPONENTS_BY_ID
 */
const COMPONENTS = [
  COMPONENT_KPI_CARD,
  COMPONENT_INFO_CARD,
  COMPONENT_PROCESS_STEP,
  COMPONENT_DATA_TABLE,
  COMPONENT_COMPARE_CARD,
  COMPONENT_TEAM_GRID,
  COMPONENT_HIGHLIGHT_QUOTE,
  COMPONENT_BIG_NUMBER_ROW
];

const COMPONENTS_BY_ID = {};
COMPONENTS.forEach(function (c) { COMPONENTS_BY_ID[c.id] = c; });

/** 按分类归组的组件，方便展示页使用 */
const COMPONENTS_BY_CATEGORY = {};
COMPONENTS.forEach(function (c) {
  if (!COMPONENTS_BY_CATEGORY[c.category]) {
    COMPONENTS_BY_CATEGORY[c.category] = [];
  }
  COMPONENTS_BY_CATEGORY[c.category].push(c);
});
